ci:
  autoupdate_schedule: monthly
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
      - id: end-of-file-fixer
      -   id: mixed-line-ending
          args: ['--fix=lf']
          description: Forces to replace line ending by the UNIX 'lf' character.
      - id: name-tests-test
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-xml
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-symlinks

  -   repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort

  -   repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0  # Use the ref you want to point at
      hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: python-check-blanket-type-ignore
      - id: python-check-blanket-noqa

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.0.281'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell  # See setup.cfg for args

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [selfcookie]
        pass_filenames: false
        additional_dependencies:
          - types-requests
          - types-certifi
          - pytest
