[project]
name = "selfcookie"
version = "0.1.0"
description = "Simple Python Cookiecutter Generator"
authors = [
    {name = "João Pinto", email = "lamego.pinto@gmail.com"},
]
dependencies = [
    "typer>=0.9.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm.scripts]

# git related
commit = 'git commit -a -m "{args}"'
status = "git status"

release = "python -m release"
selfcookie = "python -m selfcookie"

test = "pytest --cov=selfcookie --cov=release --cov-report=term-missing"
lint = "echo pre-commit run --all-files"
doc = {shell = "cd docs && mkdocs serve", help = "Start the dev server for doc preview"}

# Dependencies below MUST be managed using:
#  pdm add -dG group_name package_name, eg:
#  pdm add -dG  test pytest

[tool.pdm.dev-dependencies]
test = [
    "pdm[pytest]",
    "pytest-cov",
    "pytest>=7.4.0",
]
lint = [
    "pre-commit>=3.3.3",
]
release = [
    "jinja2>=3.1.2",
]


[tool.ruff]
line-length = 120

[tool.black]
line-length = 120
target-version = ["py311"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
testpaths = [
    "release",
    "tests"
]

[tool.coverage.run]
omit = [
    "selfcookie/__main__.py",
    "release/__main__.py",
]
