name: Publish docs to GitHub Pages
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3

      - name: Install dependencies
        run: pdm sync

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yaml
