name: Publish GitHub release
on: [push]

jobs:

  BuildAndRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create a release
    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2

      - name: Install dependencies
        run: |
          pdm sync

      - name: Build before sending to release
        run: |
          pdm build

      - name: Create the GH release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body_path: ${{ github.workspace }}-CHANGELOG.txt
