name: Test, Lint, Build and Release
on: [push]

jobs:

  all:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create a release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed to get all tags for the SCM version setup

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3

      - name: Install dependencies
        run: |
          pdm sync

      - name: Check the dynamic version
        run: |
          pdm version

      - name: Run linting and test
        run: |
          pdm lint
          pdm test

      - name: Build before sending to release
        run: |
          pdm build

      - name: Prepare for release
        run: |
          pdm release

      - name: Create the GH release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body_path: CHANGELOG.md
